### ISSUE TITLE
Parter Emotes cause cosmetics to show in first person

### ISSUE THREAD

**Issue by Cephelo** [Wet-Boys/LethalEmotesAPI#75]
When a player has cosmetics on them from any given cosmetic mod (For example, the MoreCompany cosmetics), and they join another player in emoting (whether a designated partner emote with a join circle, or just pressing V on them to do the same emote), that player's cosmetics will still be shown for them when they return to first person.  This can be extremely obtrusive to gameplay, since most of the time your vision will be obscured by any given face cosmetic you have equipped.

We were using this mod at the time: https://thunderstore.io/c/lethal-company/p/Gemumoddo/Tf2Emotes/

I'd be happy to help with testing if need be.  Thank you for such a useful API!

**Comment by Cephelo** [comment]
This also appears to occur when no cosmetics are equipped, and the default helmet is applied as well: see below image.
<img width="972" alt="Screen Shot 2024-01-11 at 2 05 21 AM" src="https://github.com/Wet-Boys/LethalEmotesAPI/assets/79186646/d1b12f04-3339-4018-9a1e-627d21f9f196">
Reproduced by using a TF2Emotes emote and then switching to another non-TF2 emote that uses the LethalEmotesAPI.

**Comment by ToastedOven** [comment]
So yeah this is an unfortunate almost unavoidable side effect of multiple third person methods colliding with each other. I'm down to look into a solution in the future, but in order for stuff like this to not happen would require basically every mod to be in compliance with each other. The best thing I would recommend is if you are playing with 3rdPerson by Verity, to turn this settings to none in emotes 
![Lethal_Company_oogKy0wBa8](https://github.com/Wet-Boys/LethalEmotesAPI/assets/49164897/9a2cfdb0-efd6-4999-9183-c94a93595a7d)
This will effectively disable all third person functionality from LethalEmotesAPI, which honestly makes sense since you are already installing your own third person mod

**Comment by ToastedOven** [comment]
I'll leave this issue open though for the future, I want to come back to this but it's not a high priority since you can just turn third person off and use the other third person mods you already have installed

**Comment by Cephelo** [comment]
I probably should've specified, but for the original bug we do not have 3rdPerson installed.  Tomorrow I'll be able to get a video of this happening for ya - I can only replicate it in multiplayer.

**Comment by Cephelo** [comment]
Here's that video demonstration I promised, it's only two minutes: https://youtu.be/P28gazLsSSA

I should've noted at the end of the video, but when he exits the terminal, his cosmetics show up again.  They aren't *removed* by accessing the terminal, it seems like they're just behind him.
I believe the reason the cosmetics aren't always on top of the player's face when bugged is because the first person perspective and the head's location on the model itself (visible in third person) do not line up - so whatever code hides the cosmetics is not functioning.

**Comment by ToastedOven** [comment]
can you send a r2modman code? I don't really want to have to sift through that whole list to add them to my profile

**Comment by Cephelo** [comment]
Whoops my bad I saw this just now, here you go: 018d00a1-b782-e1d3-d7da-fed216335cb7
Not sure how I didn't think of that

**Comment by Cephelo** [comment]
Thank you so much for finding the source of the bug and fixing it!  My friends and I really appreciate your work :)
