### ISSUE TITLE
Incompatibility with LCVR

### ISSUE THREAD

**Issue by Chikuriro** [Wet-Boys/LethalEmotesAPI#95]
I was trying to play with this mod and LCVR, but whenever I try to use the motion controls my hands get stuck in the air
![36e026de12b2a62c025ba5e92d32fdb8](https://github.com/Wet-Boys/LethalEmotesAPI/assets/156855858/61197446-ee5d-42e2-8ed9-189577590fd9)

In any update, would it be possible to adjust the movement hands-on with the controller?

**Comment by ToastedOven** [comment]
please use the template, you probably had other mods installed that broke it because contrary to what the copypasta they keep using in the LCVR server which is incorrect, emotesapi mods have been tested a few times with VR and don't cause conflicts. Don't listen to the "all emote mods break VR" bullshit, they have no idea what they are talking about.



anyway, please use the bug template so I can actually see what mods you had installed when this occurred
